### ISSUE TITLE
Should rsor::Slice implement Sync?

### ISSUE THREAD

**Issue by mgeier** [mgeier/rsor#7]
If yes, under which exact conditions on `T`?

**Comment by mbrubeck** [comment]
I believe it would be safe for `Slice` to implement `Sync` for the same reasons it is safe to implement `Send`: The only time it could be accessed on multiple threads is when it is not exclusively borrowed, and therefore is not “in use.”

It is not directly useful for `Slice` to implement `Sync`, because the only thing you can do through a shared reference (`&Slice`) is call `capacity`.  However, it may be useful in cases where a `Slice` is contained in some other type that needs to implement `Sync`.

**Comment by mgeier** [comment]
Thanks a lot @mbrubeck, that sounds very resonable!

I've implemented `Sync` in #11.
